spring:
  application:
    name: Rad.io
  profiles:
    active: local

server:
  port: 8081
  context-path: /api

---

spring:
  profiles: local

database:
  type: nitrite
  filepath: "rad-io.db"


logging:
  level:
    org:
      schlocknet: DEBUG
