spring:
  application:
    name: Rad.io
  profiles:
    active: local

server:
  port: 8081
  context-path: /api

---

spring:
  profiles: local

database:
  mongo:
    database: hcom
    host: localhost

logging:
  level:
    org:
      schlocknet: DEBUG
